[project]
name = "backend-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ananya Mengistu", email = "ananyamengisu06@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend-new = "backend_new:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
