/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BanksIndexRouteImport } from './routes/banks/index'
import { Route as BanksBankIdRouteImport } from './routes/banks/$bankId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksIndexRoute = BanksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BanksRoute,
} as any)
const BanksBankIdRoute = BanksBankIdRouteImport.update({
  id: '/$bankId',
  path: '/$bankId',
  getParentRoute: () => BanksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banks': typeof BanksRouteWithChildren
  '/compare': typeof CompareRoute
  '/converter': typeof ConverterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/banks/$bankId': typeof BanksBankIdRoute
  '/banks/': typeof BanksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/converter': typeof ConverterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/banks/$bankId': typeof BanksBankIdRoute
  '/banks': typeof BanksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banks': typeof BanksRouteWithChildren
  '/compare': typeof CompareRoute
  '/converter': typeof ConverterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/banks/$bankId': typeof BanksBankIdRoute
  '/banks/': typeof BanksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banks'
    | '/compare'
    | '/converter'
    | '/dashboard'
    | '/history'
    | '/banks/$bankId'
    | '/banks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/converter'
    | '/dashboard'
    | '/history'
    | '/banks/$bankId'
    | '/banks'
  id:
    | '__root__'
    | '/'
    | '/banks'
    | '/compare'
    | '/converter'
    | '/dashboard'
    | '/history'
    | '/banks/$bankId'
    | '/banks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanksRoute: typeof BanksRouteWithChildren
  CompareRoute: typeof CompareRoute
  ConverterRoute: typeof ConverterRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks/': {
      id: '/banks/'
      path: '/'
      fullPath: '/banks/'
      preLoaderRoute: typeof BanksIndexRouteImport
      parentRoute: typeof BanksRoute
    }
    '/banks/$bankId': {
      id: '/banks/$bankId'
      path: '/$bankId'
      fullPath: '/banks/$bankId'
      preLoaderRoute: typeof BanksBankIdRouteImport
      parentRoute: typeof BanksRoute
    }
  }
}

interface BanksRouteChildren {
  BanksBankIdRoute: typeof BanksBankIdRoute
  BanksIndexRoute: typeof BanksIndexRoute
}

const BanksRouteChildren: BanksRouteChildren = {
  BanksBankIdRoute: BanksBankIdRoute,
  BanksIndexRoute: BanksIndexRoute,
}

const BanksRouteWithChildren = BanksRoute._addFileChildren(BanksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanksRoute: BanksRouteWithChildren,
  CompareRoute: CompareRoute,
  ConverterRoute: ConverterRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
